footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.03

robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 2.0
transform_tolerance: 0.5
use_sim_time: true

resolution: 0.1

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
static_layer:
  map_topic: /map
  map_subscribe_transient_local: true
  enabled: true
  subscribe_to_updates: true
  transform_tolerance: 0.1

obstacle_layer:
  plugin: "nav2_costmap_2d::ObstacleLayer"
  enabled: true
  footprint_clearing_enabled: true
  max_obstacle_height: 2.0
  combination_method: 1
  observation_sources: robosense
  robosense:
    sensor_frame: robosense
    data_type: PointCloud2
    topic: /rs_points
    expected_update_rate: 20.0
    obstacle_max_range: 2.5
    obstacle_min_range: 0.0
    raytrace_max_range: 3.0
    raytrace_min_range: 0.0
    max_obstacle_height: 1.1 # setted to 1.1 to fiter an false detection caused an error in the robosense lidar description when gpu flag is setted to true (default: 2.0)
    min_obstacle_height: 0.1
    marking: true
    clearing: true
    inf_is_valid: false
  zed:
    sensor_frame: zed_node_camera_center
    data_type: PointCloud2
    topic: /zed_node/point_cloud/cloud_registered
    expected_update_rate: 30.0
    obstacle_max_range: 2.5
    obstacle_min_range: 0.0
    raytrace_max_range: 3.0
    raytrace_min_range: 0.0
    max_obstacle_height: 2.0
    min_obstacle_height: 0.1
    marking: true
    clearing: true
    inf_is_valid: false

voxel_layer:
  plugin: "nav2_costmap_2d::VoxelLayer"
  enabled: true
  footprint_clearing_enabled: true
  max_obstacle_height: 2.0
  publish_voxel_map: true
  z_resolution: 0.1
  origin_z: 0.0
  z_voxels: 16
  max_obstacle_height: 2.0
  publish_voxel_map: true
  unknown_threshold: 15
  mark_threshold: 0
  observation_sources: robosense zed
  combination_method: 1
  robosense:
    sensor_frame: robosense
    data_type: PointCloud2
    topic: /rs_points
    expected_update_rate: 20.0
    max_obstacle_height: 1.1 # setted to 1.1 to fiter an false detection caused an error in the robosense lidar description when gpu flag is setted to true (default: 2.0)
    min_obstacle_height: 0.1
    obstacle_max_range: 2.5
    obstacle_min_range: 0.0
    raytrace_max_range: 3.0
    raytrace_min_range: 0.0
    marking: true
    clearing: true
  zed:
    sensor_frame: zed_node_camera_center
    data_type: PointCloud2
    topic: /zed_node/point_cloud/cloud_registered
    expected_update_rate: 30.0
    max_obstacle_height: 2.0
    min_obstacle_height: 0.1
    obstacle_max_range: 2.5
    obstacle_min_range: 0.0
    raytrace_max_range: 3.0
    raytrace_min_range: 0.0
    marking: true
    clearing: true

inflation_layer:
  plugin: "nav2_costmap_2d::InflationLayer"
  enabled: true
  inflation_radius: 0.55
  cost_scaling_factor: 1.0
  inflate_unknown: false
  inflate_around_unknown: true
