footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.1

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: robosense zed
    robosense: {sensor_frame: robosense, data_type: PointCloud2, topic: rs_points, marking: true, clearing: true}
    zed: {sensor_frame: zed_node_camera_center, data_type: PointCloud2, topic: zed_node/point_cloud/cloud_registered, marking: true, clearing: true}


inflation:
    inflation_radius: 1.0
