global_frame: map
rolling_window: true
track_unknown_space: true
update_frequency: 1.0
publish_frequency: 1.0

plugins:
  - {name: obstacle_layer,                type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer,               type: "costmap_2d::InflationLayer"}
