footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.03

robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 2.0
transform_tolerance: 0.1
use_sim_time: true
rolling_window: false
resolution: 0.05

obstacle_range: 5.5
raytrace_range: 7.0

#layer definitions
static_layer:
  map_topic: /map
  map_subscribe_transient_local: true
  enabled: true
  subscribe_to_updates: true
  transform_tolerance: 0.1

obstacle_layer:
  plugin: "nav2_costmap_2d::ObstacleLayer"
  enabled: true
  footprint_clearing_enabled: true
  max_obstacle_height: 1.2
  combination_method: 1
  observation_sources: rslidar zed
  rslidar:
    sensor_frame: rslidar
    data_type: PointCloud2
    topic: /rslidar_points
    expected_update_rate: 0.2
    obstacle_max_range: 5.5
    obstacle_min_range: 0.5
    raytrace_max_range: 7.0
    raytrace_min_range: 0.0
    max_obstacle_height: 1.2
    min_obstacle_height: 0.1
    marking: true
    clearing: true
    inf_is_valid: false
  zed:
    sensor_frame: zed_left_camera_frame
    data_type: PointCloud2
    topic: /zed_node/point_cloud/cloud_registered
    expected_update_rate: 0.35
    obstacle_max_range: 2.5
    obstacle_min_range: 0.0
    raytrace_max_range: 3.0
    raytrace_min_range: 0.0
    max_obstacle_height: 1.2
    min_obstacle_height: 0.1
    marking: true
    clearing: true
    inf_is_valid: false

voxel_layer:
  plugin: "nav2_costmap_2d::VoxelLayer"
  enabled: true
  footprint_clearing_enabled: true
  max_obstacle_height: 15.0
  publish_voxel_map: true
  z_resolution: 0.1
  origin_z: 0.0
  z_voxels: 16
  max_obstacle_height: 1.2
  publish_voxel_map: true
  unknown_threshold: 15
  mark_threshold: 0
  observation_sources: rslidar zed
  combination_method: 1
  rslidar:
    sensor_frame: rslidar
    data_type: PointCloud2
    topic: /rslidar_points
    expected_update_rate: 0.2
    max_obstacle_height: 1.2
    min_obstacle_height: 0.1
    obstacle_max_range: 7.0
    obstacle_min_range: 0.5
    raytrace_max_range: 6.0
    raytrace_min_range: 0.0
    marking: true
    clearing: true
  zed:
    sensor_frame: zed_left_camera_frame
    data_type: PointCloud2
    topic: /zed_node/point_cloud/cloud_registered
    expected_update_rate: 0.35
    max_obstacle_height: 1.2
    min_obstacle_height: 0.1
    obstacle_max_range: 2.5
    obstacle_min_range: 0.0
    raytrace_max_range: 2.0
    raytrace_min_range: 0.0
    marking: true
    clearing: true

inflation_layer:
  plugin: "nav2_costmap_2d::InflationLayer"
  enabled: true
  inflation_radius: 0.5
  cost_scaling_factor: 5.0
  inflate_unknown: false
  inflate_around_unknown: false
