frequency: 40
delay: 2.0
magnetic_declination_radians: 0.01745
yaw_offset: 1.570963
zero_altitude: false
broadcast_cartesian_transform: false
publish_filtered_gps: true
use_odometry_yaw: false
wait_for_datum: false
#datum: [48.711252, 2.217757, 0, "map", "base_link"]
