frequency: 30
delay: 3.0
magnetic_declination_radians: 0.0244
yaw_offset: 0.0
zero_altitude: false
broadcast_cartesian_transform: true
publish_filtered_gps: true
use_odometry_yaw: false
wait_for_datum: false
