frequency: 40
delay: 3.0
magnetic_declination_radians: 0.0
yaw_offset: 1.5707963
zero_altitude: true
broadcast_cartesian_transform: true
publish_filtered_gps: true
use_odometry_yaw: false
wait_for_datum: false
