frequency: 30
delay: 3.0
magnetic_declination_radians: 0.0
datum: [48.711254, 2.217765, 0.0, odom, base_link]
yaw_offset: 1.570796327  # IMU reads 0 facing magnetic north, not east
zero_altitude: true
broadcast_cartesian_transform: true
publish_filtered_gps: true
use_odometry_yaw: false
wait_for_datum: false